support free threading
ntamas/crcmod-plus pull request #1
Opened 2024-12-28 17:39 UTC by synodriver

2024-12-28 19:17 UTC, ntamas requested changes
Thank you for your contribution! Just one minor comment (see above) and I guess this can be merged. I'll update the CI configuration separately to compile wheels for free-threaded Python.

2024-12-28 19:17 UTC, ntamas commented on setup.py
> +def is_freethread():
Is there any reason why this check should not simply use `sysconfig.get_config_var("Py_GIL_DISABLED")` as suggested by [the official docs](https://docs.python.org/3/howto/free-threading-extensions.html#limited-c-api-and-stable-abi)?

2025-01-11 15:03 UTC, synodriver commented on setup.py
> +def is_freethread():
Ok, I'll fix that.

2025-01-11 18:08 UTC, merged

2025-01-11 18:08 UTC, ntamas commented
Thanks!